return {
  pde = {
    ai = false,
    angular = false,
    cpp = false,
    csharp = true,
    docker = true,
    elixir = false,
    flutter = false,
    go = false,
    html = false,
    java = false,
    json = true,
    julia = false,
    jupyter = true,
    kotlin = false,
    lua = true,
    python = true,
    r = false,
    react = false,
    ruby = false,
    rust = false,
    scala = false,
    solidity = false,
    svelte = false,
    tailwind = false,
    terraform = false,
    typescript = true,
    vuejs = false,
  },
}
