return {
  pde = {
    ai = false,
    angular = false,
    cpp = false,
    csharp = true,
    docker = false,
    elixir = false,
    flutter = false,
    go = false,
    html = false,
    java = false,
    json = false,
    julia = false,
    jupyter = false,
    kotlin = false,
    lua = false,
    python = false,
    r = false,
    react = false,
    ruby = false,
    rust = false,
    scala = false,
    solidity = false,
    svelte = false,
    tailwind = false,
    terraform = false,
    typescript = false,
    vuejs = false,
  },
}
